// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.WebService.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SchedulePeriodTests")]
    public partial class SchedulePeriodTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "SchedulePeriodTests.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SchedulePeriodTests", "\tAs a user \r\n\tI want to be able to save and edit shifts\r\n\tso that I can create a " +
                    "schedule", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Schedule period")]
        [NUnit.Framework.CategoryAttribute("CreateLocation")]
        [NUnit.Framework.CategoryAttribute("CreateLocations")]
        [NUnit.Framework.CategoryAttribute("LocationForAnotherOrganisation")]
        [NUnit.Framework.CategoryAttribute("CreateArea")]
        [NUnit.Framework.CategoryAttribute("CreateAreaAnotherOrganisation")]
        [NUnit.Framework.CategoryAttribute("CreateRole")]
        [NUnit.Framework.CategoryAttribute("CreateRoles")]
        [NUnit.Framework.CategoryAttribute("CreateRoleForAnotherOrganisation")]
        [NUnit.Framework.CategoryAttribute("CreateDepartment")]
        [NUnit.Framework.CategoryAttribute("CreateAnotherDepartmentSameLocation")]
        [NUnit.Framework.CategoryAttribute("CreateDepartmentAnotherLocationSameOrganisation")]
        [NUnit.Framework.CategoryAttribute("CreateDepartmentAnotherOrganisation")]
        [NUnit.Framework.CategoryAttribute("CreateJobTitle")]
        [NUnit.Framework.CategoryAttribute("CreateEmployee")]
        [NUnit.Framework.CategoryAttribute("CreateAnotherOrganisationEmployee")]
        [NUnit.Framework.CategoryAttribute("CreateEmployees")]
        [NUnit.Framework.CategoryAttribute("CreateMainAssignment")]
        [NUnit.Framework.CategoryAttribute("MainAssignmentForEmployeeAnotherOrganisation")]
        [NUnit.Framework.TestCaseAttribute("1.InTeFutureWithBreaks", "15", "25", "2022-01-02 08:09", "2022-12-02 10:09", null)]
        [NUnit.Framework.TestCaseAttribute("2.WithoutBreaks", "0", "0", "2022-01-02 08:09", "2022-1-02 10:09", null)]
        [NUnit.Framework.TestCaseAttribute("3.ShiftInThePast", "15", "25", "2019-01-15 08:09", "2019-01-15 10:09", null)]
        public virtual void GetSchedulePeriod(string testCase, string break1Minutes, string break2Minutes, string startDateTime, string endDateTime, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreateLocation",
                    "CreateLocations",
                    "LocationForAnotherOrganisation",
                    "CreateArea",
                    "CreateAreaAnotherOrganisation",
                    "CreateRole",
                    "CreateRoles",
                    "CreateRoleForAnotherOrganisation",
                    "CreateDepartment",
                    "CreateAnotherDepartmentSameLocation",
                    "CreateDepartmentAnotherLocationSameOrganisation",
                    "CreateDepartmentAnotherOrganisation",
                    "CreateJobTitle",
                    "CreateEmployee",
                    "CreateAnotherOrganisationEmployee",
                    "CreateEmployees",
                    "CreateMainAssignment",
                    "MainAssignmentForEmployeeAnotherOrganisation"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Schedule period", null, @__tags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 27
testRunner.Given("create assignments with different roles", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table21.AddRow(new string[] {
                            "StartDateTime",
                            "2030-01-15 07:09"});
                table21.AddRow(new string[] {
                            "EndDateTime",
                            "2030-01-15 08:00"});
                table21.AddRow(new string[] {
                            "ChargedDate",
                            "2030-01-15"});
#line 28
    testRunner.Given("SchedulePeriod data is created for departments", ((string)(null)), table21, "Given ");
#line hidden
#line 34
 testRunner.Given("the /locations/{locationId}/departments/{departmentId}/from/{from}/to/{to}/schedu" +
                        "le-period/ resource", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value"});
                table22.AddRow(new string[] {
                            "locationId",
                            "$Location.ID"});
                table22.AddRow(new string[] {
                            "departmentId",
                            "$Department.ID"});
                table22.AddRow(new string[] {
                            "from",
                            "2030-01-15"});
                table22.AddRow(new string[] {
                            "to",
                            "2030-01-18"});
#line 35
  testRunner.And("the following url segments", ((string)(null)), table22, "And ");
#line hidden
#line 42
 testRunner.When("a GET request is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
     testRunner.And("response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Schedule period for transition shift")]
        [NUnit.Framework.CategoryAttribute("CreateLocation")]
        [NUnit.Framework.CategoryAttribute("CreateArea")]
        [NUnit.Framework.CategoryAttribute("CreateRole")]
        [NUnit.Framework.CategoryAttribute("CreateDepartment")]
        [NUnit.Framework.CategoryAttribute("CreateJobTitle")]
        [NUnit.Framework.CategoryAttribute("CreateEmployee")]
        [NUnit.Framework.CategoryAttribute("CreateEmployees")]
        [NUnit.Framework.CategoryAttribute("CreateMainAssignment")]
        public virtual void GetSchedulePeriodForTransitionShift()
        {
            string[] tagsOfScenario = new string[] {
                    "CreateLocation",
                    "CreateArea",
                    "CreateRole",
                    "CreateDepartment",
                    "CreateJobTitle",
                    "CreateEmployee",
                    "CreateEmployees",
                    "CreateMainAssignment"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Schedule period for transition shift", null, new string[] {
                        "CreateLocation",
                        "CreateArea",
                        "CreateRole",
                        "CreateDepartment",
                        "CreateJobTitle",
                        "CreateEmployee",
                        "CreateEmployees",
                        "CreateMainAssignment"});
#line 62
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table23.AddRow(new string[] {
                            "StartDateTime",
                            "2030-02-01 02:09"});
                table23.AddRow(new string[] {
                            "EndDateTime",
                            "2030-02-02 08:00"});
                table23.AddRow(new string[] {
                            "ChargedDate",
                            "2030-02-02"});
#line 63
    testRunner.Given("create and save shift in db", ((string)(null)), table23, "Given ");
#line hidden
#line 69
 testRunner.Given("the /locations/{locationId}/departments/{departmentId}/from/{from}/to/{to}/schedu" +
                        "le-period/ resource", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value"});
                table24.AddRow(new string[] {
                            "locationId",
                            "$Location.ID"});
                table24.AddRow(new string[] {
                            "departmentId",
                            "$Department.ID"});
                table24.AddRow(new string[] {
                            "from",
                            "2030-02-01"});
                table24.AddRow(new string[] {
                            "to",
                            "2030-02-02"});
#line 70
  testRunner.And("the following url segments", ((string)(null)), table24, "And ");
#line hidden
#line 77
 testRunner.When("a GET request is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 79
 testRunner.When("a GET request is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 81
     testRunner.And("response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Schedule period for employee with assignment in the future or in the past")]
        [NUnit.Framework.CategoryAttribute("CreateLocation")]
        [NUnit.Framework.CategoryAttribute("CreateArea")]
        [NUnit.Framework.CategoryAttribute("CreateRole")]
        [NUnit.Framework.CategoryAttribute("CreateDepartment")]
        [NUnit.Framework.CategoryAttribute("CreateJobTitle")]
        [NUnit.Framework.CategoryAttribute("CreateEmployee")]
        [NUnit.Framework.CategoryAttribute("CreateEmployees")]
        [NUnit.Framework.TestCaseAttribute("1.AssignmentInTheFuture", "2030-02-06", "", "2030-02-04", "2030-02-06", null)]
        [NUnit.Framework.TestCaseAttribute("2.AssignmentInThePast", "2018-02-04", "2019-11-11", "2019-11-11", "2019-11-12", null)]
        public virtual void GetSchedulePeriodForEmployeeWithAssignmentInTheFutureOrInThePast(string testCase, string fromDate, string toDate, string from, string to, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreateLocation",
                    "CreateArea",
                    "CreateRole",
                    "CreateDepartment",
                    "CreateJobTitle",
                    "CreateEmployee",
                    "CreateEmployees"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Schedule period for employee with assignment in the future or in the past", null, @__tags);
#line 91
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table25.AddRow(new string[] {
                            "FromDate",
                            string.Format("{0}", fromDate)});
                table25.AddRow(new string[] {
                            "ToDate",
                            string.Format("{0}", toDate)});
#line 92
    testRunner.Given("create assignment", ((string)(null)), table25, "Given ");
#line hidden
#line 96
 testRunner.Given("the /locations/{locationId}/departments/{departmentId}/from/{from}/to/{to}/schedu" +
                        "le-period/ resource", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value"});
                table26.AddRow(new string[] {
                            "locationId",
                            "$Location.ID"});
                table26.AddRow(new string[] {
                            "departmentId",
                            "$Department.ID"});
                table26.AddRow(new string[] {
                            "from",
                            string.Format("{0}", from)});
                table26.AddRow(new string[] {
                            "to",
                            string.Format("{0}", to)});
#line 97
  testRunner.And("the following url segments", ((string)(null)), table26, "And ");
#line hidden
#line 103
 testRunner.When("a GET request is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 105
     testRunner.And("response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Schedule period for employee with main and non main assignments with differen" +
            "t roles and departments")]
        [NUnit.Framework.CategoryAttribute("CreateLocation")]
        [NUnit.Framework.CategoryAttribute("CreateArea")]
        [NUnit.Framework.CategoryAttribute("CreateRole")]
        [NUnit.Framework.CategoryAttribute("CreateAnotherRole")]
        [NUnit.Framework.CategoryAttribute("CreateDepartment")]
        [NUnit.Framework.CategoryAttribute("CreateAnotherDepartmentSameLocation")]
        [NUnit.Framework.CategoryAttribute("CreateJobTitle")]
        [NUnit.Framework.CategoryAttribute("CreateEmployee")]
        [NUnit.Framework.TestCaseAttribute("1.AssignmentInTheFuture", "2030-03-02", "", "2030-03-03", "", "2030-03-01", "2030-03-04", null)]
        public virtual void GetSchedulePeriodForEmployeeWithMainAndNonMainAssignmentsWithDifferentRolesAndDepartments(string testCase, string fromDateMain, string toDateMain, string fromDateNonMain, string toDateNonMain, string from, string to, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreateLocation",
                    "CreateArea",
                    "CreateRole",
                    "CreateAnotherRole",
                    "CreateDepartment",
                    "CreateAnotherDepartmentSameLocation",
                    "CreateJobTitle",
                    "CreateEmployee"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Schedule period for employee with main and non main assignments with differen" +
                    "t roles and departments", null, @__tags);
#line 122
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table27.AddRow(new string[] {
                            "FromDate",
                            string.Format("{0}", fromDateMain)});
                table27.AddRow(new string[] {
                            "ToDate",
                            string.Format("{0}", toDateMain)});
#line 123
    testRunner.Given("create assignment", ((string)(null)), table27, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table28.AddRow(new string[] {
                            "FromDate",
                            string.Format("{0}", fromDateNonMain)});
                table28.AddRow(new string[] {
                            "ToDate",
                            string.Format("{0}", toDateNonMain)});
#line 127
  testRunner.And("create non main assignment for another department, same location", ((string)(null)), table28, "And ");
#line hidden
#line 131
     testRunner.And("the /locations/{locationId}/departments/{departmentId}/from/{from}/to/{to}/schedu" +
                        "le-period/ resource", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value"});
                table29.AddRow(new string[] {
                            "locationId",
                            "$Location.ID"});
                table29.AddRow(new string[] {
                            "departmentId",
                            "$Department.ID"});
                table29.AddRow(new string[] {
                            "from",
                            string.Format("{0}", from)});
                table29.AddRow(new string[] {
                            "to",
                            string.Format("{0}", to)});
#line 132
  testRunner.And("the following url segments", ((string)(null)), table29, "And ");
#line hidden
#line 138
 testRunner.When("a GET request is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 140
     testRunner.And("response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Schedule period for employee with shifts for non main assignments with anothe" +
            "r department, same location")]
        [NUnit.Framework.CategoryAttribute("CreateLocation")]
        [NUnit.Framework.CategoryAttribute("CreateArea")]
        [NUnit.Framework.CategoryAttribute("CreateRole")]
        [NUnit.Framework.CategoryAttribute("CreateAnotherRole")]
        [NUnit.Framework.CategoryAttribute("CreateDepartment")]
        [NUnit.Framework.CategoryAttribute("CreateAnotherDepartmentSameLocation")]
        [NUnit.Framework.CategoryAttribute("CreateJobTitle")]
        [NUnit.Framework.CategoryAttribute("CreateEmployee")]
        [NUnit.Framework.TestCaseAttribute("1.AssignmentInTheFuture", "2030-03-05", "", "2030-03-06", "", "2030-03-04", "2030-03-07", null)]
        public virtual void GetSchedulePeriodForEmployeeWithShiftsForNonMainAssignmentsWithAnotherDepartmentSameLocation(string testCase, string fromDateMain, string toDateMain, string fromDateNonMain, string toDateNonMain, string from, string to, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreateLocation",
                    "CreateArea",
                    "CreateRole",
                    "CreateAnotherRole",
                    "CreateDepartment",
                    "CreateAnotherDepartmentSameLocation",
                    "CreateJobTitle",
                    "CreateEmployee"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Schedule period for employee with shifts for non main assignments with anothe" +
                    "r department, same location", null, @__tags);
#line 156
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table30.AddRow(new string[] {
                            "FromDate",
                            string.Format("{0}", fromDateMain)});
                table30.AddRow(new string[] {
                            "ToDate",
                            string.Format("{0}", toDateMain)});
#line 157
    testRunner.Given("create assignment", ((string)(null)), table30, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table31.AddRow(new string[] {
                            "FromDate",
                            string.Format("{0}", fromDateNonMain)});
                table31.AddRow(new string[] {
                            "ToDate",
                            string.Format("{0}", toDateNonMain)});
#line 161
  testRunner.And("create non main assignment for another department, same location", ((string)(null)), table31, "And ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table32.AddRow(new string[] {
                            "StartDateTime",
                            "2030-03-05  08:09"});
                table32.AddRow(new string[] {
                            "EndDateTime",
                            "2030-03-05  10:00"});
                table32.AddRow(new string[] {
                            "ChargedDate",
                            "2030-03-05"});
#line 165
  testRunner.And("create and save shift in db", ((string)(null)), table32, "And ");
#line hidden
                TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table33.AddRow(new string[] {
                            "StartDateTime",
                            "2030-03-06 08:09"});
                table33.AddRow(new string[] {
                            "EndDateTime",
                            "2030-03-06 10:00"});
                table33.AddRow(new string[] {
                            "ChargedDate",
                            "2030-03-06"});
#line 170
   testRunner.And("create and save shift in db for another department and role", ((string)(null)), table33, "And ");
#line hidden
#line 175
     testRunner.And("the /locations/{locationId}/departments/{departmentId}/from/{from}/to/{to}/schedu" +
                        "le-period/ resource", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value"});
                table34.AddRow(new string[] {
                            "locationId",
                            "$Location.ID"});
                table34.AddRow(new string[] {
                            "departmentId",
                            "$Department.ID"});
                table34.AddRow(new string[] {
                            "from",
                            string.Format("{0}", from)});
                table34.AddRow(new string[] {
                            "to",
                            string.Format("{0}", to)});
#line 176
  testRunner.And("the following url segments", ((string)(null)), table34, "And ");
#line hidden
#line 182
 testRunner.When("a GET request is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 184
     testRunner.And("response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Schedule period for employee with shifts for non main assignments with anothe" +
            "r department, different location")]
        [NUnit.Framework.CategoryAttribute("CreateLocation")]
        [NUnit.Framework.CategoryAttribute("CreateArea")]
        [NUnit.Framework.CategoryAttribute("CreateRole")]
        [NUnit.Framework.CategoryAttribute("CreateAnotherRole")]
        [NUnit.Framework.CategoryAttribute("CreateDepartment")]
        [NUnit.Framework.CategoryAttribute("CreateAnotherDepartmentSameLocation")]
        [NUnit.Framework.CategoryAttribute("CreateJobTitle")]
        [NUnit.Framework.CategoryAttribute("CreateEmployee")]
        [NUnit.Framework.TestCaseAttribute("1.AssignmentInTheFuture", "2030-03-05", "", "2030-03-06", "", "2030-03-04", "2030-03-07", null)]
        public virtual void GetSchedulePeriodForEmployeeWithShiftsForNonMainAssignmentsWithAnotherDepartmentDifferentLocation(string testCase, string fromDateMain, string toDateMain, string fromDateNonMain, string toDateNonMain, string from, string to, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreateLocation",
                    "CreateArea",
                    "CreateRole",
                    "CreateAnotherRole",
                    "CreateDepartment",
                    "CreateAnotherDepartmentSameLocation",
                    "CreateJobTitle",
                    "CreateEmployee"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Schedule period for employee with shifts for non main assignments with anothe" +
                    "r department, different location", null, @__tags);
#line 199
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table35.AddRow(new string[] {
                            "FromDate",
                            string.Format("{0}", fromDateMain)});
                table35.AddRow(new string[] {
                            "ToDate",
                            string.Format("{0}", toDateMain)});
#line 200
    testRunner.Given("create assignment", ((string)(null)), table35, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table36.AddRow(new string[] {
                            "FromDate",
                            string.Format("{0}", fromDateNonMain)});
                table36.AddRow(new string[] {
                            "ToDate",
                            string.Format("{0}", toDateNonMain)});
#line 204
  testRunner.And("create non main assignment for another location, same organisation", ((string)(null)), table36, "And ");
#line hidden
                TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table37.AddRow(new string[] {
                            "StartDateTime",
                            "2030-03-05  08:09"});
                table37.AddRow(new string[] {
                            "EndDateTime",
                            "2030-03-05  10:00"});
                table37.AddRow(new string[] {
                            "ChargedDate",
                            "2030-03-05"});
#line 208
  testRunner.And("create and save shift in db", ((string)(null)), table37, "And ");
#line hidden
                TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table38.AddRow(new string[] {
                            "StartDateTime",
                            "2030-03-06 08:09"});
                table38.AddRow(new string[] {
                            "EndDateTime",
                            "2030-03-06 10:00"});
                table38.AddRow(new string[] {
                            "ChargedDate",
                            "2030-03-06"});
#line 213
   testRunner.And("create and save shift in db for another location, same organisation", ((string)(null)), table38, "And ");
#line hidden
#line 218
     testRunner.And("the /locations/{locationId}/departments/{departmentId}/from/{from}/to/{to}/schedu" +
                        "le-period/ resource", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value"});
                table39.AddRow(new string[] {
                            "locationId",
                            "$Location.ID"});
                table39.AddRow(new string[] {
                            "departmentId",
                            "$Department.ID"});
                table39.AddRow(new string[] {
                            "from",
                            string.Format("{0}", from)});
                table39.AddRow(new string[] {
                            "to",
                            string.Format("{0}", to)});
#line 219
  testRunner.And("the following url segments", ((string)(null)), table39, "And ");
#line hidden
#line 225
 testRunner.When("a GET request is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 227
     testRunner.And("response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
